djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('priceapp.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(
            settings.STATIC_URL,
            document_root=settings.STATICFILES_DIRS
        )
    )

priceapp/urls.py
"""В модуле прописаны urls для представлений приложения."""

from django.urls import path

from .views import (
    PrintSheetView,
    PrintSheetDelete,
    PrintSheetList,
    ProductICQUpdateView,
    ProductConfirmUpdateView,
    ProductUpdateView,
    ProductCreateView,
    MissingProductFormView,
    update_instruction_get,
)


app_name = 'priceapp'

urlpatterns = [
    path('', PrintSheetDelete.as_view(), name='printsheet_delete'),
    path('scaner/', PrintSheetView.as_view(), name='printsheet_create'),
    path('print/', PrintSheetList.as_view(), name='printsheet_print'),
    path('new-product/', ProductCreateView.as_view(), name='product_create'),
    path('update/', ProductUpdateView.as_view(), name='product_update'),
    path(
        'update/icq/',
        ProductICQUpdateView.as_view(),
        name='product_icq_update'
    ),
    path(
        'update/confirm/',
        ProductConfirmUpdateView.as_view(),
        name='product_confirm_update'
    ),
    path(
        'update/add-missing/',
        MissingProductFormView.as_view(),
        name='missingproduct_form'
    ),
    path(
        'update/instruction/',
        update_instruction_get,
        name='update_instruction'
    ),
]

priceapp/forms.py
"""
Модуль хранит в себе формы для работы приложения.

Помимо обычных форм. В модуле используется объявление форм-сетов.
"""

from django import forms
from django.forms import modelformset_factory

from .models import Tag, UpdateProduct, MissingProduct


# Formset используется при подтверждении обновления цен Товаров.
ProductConfirmUpdateSet = modelformset_factory(
    UpdateProduct,
    fields=('name', 'price', 'old_price', 'red_price')
)


# FormSet используется для добавления всех Товаров, ненайденных в БД при
# обновлении.
MissingProductFormSet = modelformset_factory(
    MissingProduct,
    fields=(
        'sku',
        'ean',
        'name',
        'category',
        'country',
        'price',
        'old_price',
        'red_price'
    )
)


class PrintSheetForm(forms.Form):
    """Форма для сканирования штрихкодов с упаковок товаров и передачи \
    информации об используемом макете ценников."""

    input_line = forms.CharField(
        max_length=100,
        label='Штрихкод/Название'
    )
    size = forms.CharField(
        max_length=5,
        widget=forms.HiddenInput()
    )
    is_discount = forms.CharField(
        max_length=5,
        widget=forms.HiddenInput()
    )


class PrintSheetFreeForm(forms.Form):
    """Форма для добавления в Лист печати ценников товаров по уценки."""

    name = forms.CharField(
        label='Наименование',
        widget=forms.TextInput(
            attrs={
                'class': 'form-input',
                'placeholder': 'WF-1000XM4',
                'type': 'text',
                'style': 'min-height: 30px; height: 30px;'
            }
        )
    )
    old_price = forms.DecimalField(
        label='Старая цена',
        widget=forms.TextInput(
            attrs={
                'class': 'form-input',
                'placeholder': '19990',
                'type': 'text',
                'style': (
                    'min-width: 150px; width:150px; '
                    'min-height: 30px; height: 30px'
                )
            }
        )
    )
    price = forms.DecimalField(
        label='Цена',
        widget=forms.TextInput(
            attrs={
                'class': 'form-input',
                'placeholder': '15990',
                'type': 'text',
                'style': (
                    'min-width: 150px; width:150px; '
                    'min-height: 30px; height: 30px'
                )
            }
        )
    )
    discount_type = forms.CharField(
        label='Причина скидки',
        widget=forms.TextInput(
            attrs={
                'class': 'form-input',
                'placeholder': 'Без упаковки',
                'value': 'Акция !!!',
                'type': 'text',
                'style': 'min-height: 30px; height: 30px'
            }
        )
    )
    red_price = forms.BooleanField(
        label='Красный ценник',
        widget=forms.CheckboxInput(
            attrs={
                'class': 'toggle',
                'type': 'checkbox',
                'style': (
                    'min-width: 50px; width: 50px; '
                    'min-height: 30px; height: 30px;'
                )
            }
        ),
        required=False
    )
    tag = forms.ModelChoiceField(
        label='Размер ценника',
        queryset=Tag.objects.filter(is_discount=True),
        widget=forms.Select(
            attrs={
                'class': 'form-input',
                'type': 'text',
                'style': 'min-height: 30px; height: 30px'
            },
        )
    )


class ProductICQUpdateForm(forms.Form):
    """Форма для обновления цен из текстовой информации, полученной по \
    средствам мессенджера ICQ."""

    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-text-update-icq',
                'cols': 40,
                'rows': 15
            }
        ),
        label='Вставьте текст из ICQ со списком товаров и цен.'
    )


class FileDownloadForm(forms.Form):
    """Форма для обновления цен из файла при новой поставке."""

    file = forms.FileField()

priceapp/views.py
"""
В модуле собраны все представления для работы приложения.

Все обработки позволяют реализовать требуемый функционал.
"""

import re
from csv import DictReader
from io import TextIOWrapper

from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django.views import View
from django.views.generic import CreateView

from .models import (
    PrintSheet,
    Product,
    Tag,
    UpdateProduct,
    MissingProduct, Category, Country,
)
from .forms import (
    PrintSheetForm,
    PrintSheetFreeForm,
    ProductICQUpdateForm,
    ProductConfirmUpdateSet,
    FileDownloadForm,
    MissingProductFormSet,
)

before_redirect_url: str = ''
last_scan: dict = {
    'tag': {
        'size': 'big',
        'is_discount': False
    },
    'product': 'Список пуст'
}
missing_products_flag: bool = False


class PrintSheetDelete(View):
    """Стартовое представление которое очищает таблицы \
    `Ценники для печати`, `Обновляемые товары` и `Ненайденные товары`, \
    после чего перенаправляет на страницу формирования печати ценников."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Метод обрабатывает get запрос, очищает таблиц \
        и перенаправляет на страницу формирования печати.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        global last_scan
        PrintSheet.objects.all().delete()
        UpdateProduct.objects.all().delete()
        MissingProduct.objects.all().delete()
        last_scan = {
            'tag': {
                'size': 'big',
                'is_discount': False
            },
            'product': 'Список пуст'
        }
        return redirect(reverse('priceapp:printsheet_create'))


class PrintSheetView(View):
    """Представление формирует список ценников для печати."""

    tag_list = (
        {'size': 'big', 'is_discount': (False, 'false')},
        {'size': 'big', 'is_discount': (True, 'true')},
        {'size': 'small', 'is_discount': (False, 'false')},
        {'size': 'small', 'is_discount': (True, 'true')},
    )

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Метод обрабатывает get запрос, использует две формы \
        для обработки: форма поиска по Товарам и свободная \
        форма для формирования ценников по уценки.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        form = PrintSheetForm()
        free_form = PrintSheetFreeForm()
        context = {
            'form': form,
            'free_form': free_form,
            'tag_list': self.tag_list,
            'last_scan': last_scan
        }
        if request.session.get('message_user'):
            context['message_user'] = request.session['message_user']
            request.session.pop('message_user')
        return render(
            request,
            'priceapp/printsheet_form.html',
            context=context
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        """
        Метод формирует список ценников для печати, \
        обрабатывая для этого формы.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        global last_scan
        product = None
        form = PrintSheetForm(request.POST)
        free_form = PrintSheetFreeForm(request.POST)
        tag = last_scan['tag']
        discount_type = 'Акция !!!'
        if form.is_valid():
            form = form.cleaned_data
            input_line = form['input_line']
            size = form['size']
            is_discount = form['is_discount'] == 'true'
            tag = Tag.objects.get(size=size, is_discount=is_discount)
            product = (
                Product.objects.filter(
                    Q(ean=input_line) | Q(name__iexact=input_line)
                )
                .values(
                    'name',
                    'category',
                    'country',
                    'price',
                    'old_price',
                    'red_price'
                )
                .first()
            )
            if not product:
                request.session['message_user'] = input_line

        if free_form.is_valid():
            form = free_form.cleaned_data
            tag = form['tag']
            product = (
                Product.objects
                .filter(name__iexact=form['name'])
                .values(
                    'name',
                    'category',
                    'country',
                )
                .first()
            )
            if product:
                discount_type = form['discount_type']
                name = product['name']
                if tag.size == 'small':
                    product['name'] = f'{name} {discount_type}'
                product['price'] = form['price']
                product['old_price'] = form['old_price']
                product['red_price'] = form['red_price']
            else:
                request.session['message_user'] = form['name']
        last_scan['tag'] = tag
        if product:
            last_scan['product'] = product['name']
            product['category'] = (
                Category.objects.only('name')
                .get(id=product['category'])
                .name
            )
            product['country'] = (
                Country.objects.only('name')
                .get(id=product['country'])
                .name
            )
            PrintSheet.objects.create(
                tag=tag,
                discount_type=discount_type,
                **product
            )

        return redirect(reverse('priceapp:printsheet_create'))


class PrintSheetList(View):
    """Представление формирует лист печати ценников."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Метод обрабатывает get запрос, проходит по списку \
        ценников для печати и формирует листы размером A4.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        max_height = 290
        max_width = 180
        printsheet_list = PrintSheet.objects.all()
        size_list = ['big', 'small']
        page_list = [[]]
        height = 0
        width = 0
        for size in size_list:
            tag_list = printsheet_list.filter(tag__size=size)
            for tag in tag_list:
                page_list[-1].append(tag)
                width += tag.tag.width
                if width == max_width:
                    height += tag.tag.height
                    width = 0
                if height + tag.tag.height > max_height:
                    page_list.append([])
                    height = 0
        context = {
            'page_list': page_list
        }
        return render(
            request,
            'priceapp/print_tags.html',
            context=context
        )


class ProductICQUpdateView(View):
    """Представление обрабатывает обновление цен по \
    полученной информации от руководства через ICQ."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """
        Метод обрабатывает get запрос. В начале обработки \
        происходит удаление всех объектов в Обновляемых \
        товарах и в Ненайденных товарах.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        UpdateProduct.objects.all().delete()
        MissingProduct.objects.all().delete()
        form = ProductICQUpdateForm()
        context = {
            'form': form
        }
        return render(
            request,
            'priceapp/product_icq_update.html',
            context=context
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        """
        Метод обрабатывает post запрос. Из полученного текста \
        выделяются строки с товаром и новой ценой и формируются \
        два списка: Обновляемые товары и Ненайденные в базе \
        товары.

        :param request: HttpRequest.
        :return: HttpResponse.
        """
        global before_redirect_url, missing_products_flag
        before_redirect_url = request.path
        form = ProductICQUpdateForm(request.POST)
        update_product_list = []
        missing_product_list = []
        if form.is_valid():
            form = form.cleaned_data
            text = form['text'].split('\r\n')
            regex = r'\s{1,2}\-{1,3}\s{0,2}'
            update_list = map(
                lambda x: [elem.strip() for elem in re.split(regex, x)],
                text
            )
            for product in update_list:
                if len(product) == 2:
                    product.append('0')
                    name, price, old_price = product
                else:
                    continue
                product = Product.objects.filter(name=name).first()
                if product:
                    update_product_list.append(
                        UpdateProduct(
                            name=product.name,
                            price=price,
                            old_price=old_price,
                            red_price=product.red_price
                        )
                    )
                else:
                    missing_product_list.append(
                        MissingProduct(
                            name=name,
                            price=price,
                            old_price=old_price
                        )
                    )
        if missing_product_list:
            MissingProduct.objects.bulk_create(missing_product_list)
            missing_products_flag = True
        if update_product_list:
            UpdateProduct.objects.bulk_create(update_product_list)
            return redirect(reverse('priceapp:product_confirm_update'))
        return redirect(reverse('priceapp:missingproduct_form'))


class ProductUpdateView(View):

templates/priceapp/base.html
{% load static %}
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]>
<!-->
<html lang="ru">
<!--
<![endif]-->
<head>
    <title>Ценники</title>
    <meta name="description" content="Описание страницы">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}"
          as="font">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}"
          as="font">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}"
          as="font">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}"
          as="font">
    <link rel="preload"
          href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}"
          as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}">
    </script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script>
    <![endif]-->
    {% block head_script %}{% endblock %}
</head>
<body class="Site">
<!--if lt IE 8
p.error-browser
| Ваш браузер&nbsp;
em устарел!&nbsp;
a(href="http://browsehappy.com/") Выберите новую версию
+s
| браузера здесь&nbsp;
| для правильного отображения сайта.
-->
<header class="Header">
    <div class="ControlPanel">
    </div>
    <div class="wrap">
        <div class="row Header-rowMain">
            <nav class="row-block row-block_right Header-menu">
                <div class="menuModal" id="navigate">
                    <ul class="menu menu_main">
                        <li style="margin-right: 150px">
                            <em>&#174;БоровецТМ&#8482; 	&#8212; 2023</em>
                        </li>
                        <li class="menu-item">
                            <span class="menu-label menu-label_success">
								Печать&nbsp;ценников
							</span>
                            <a class="menu-link"
                               href="{% url 'priceapp:printsheet_delete' %}">
                                Сканер штрих-кода
                            </a>
                        </li>
                        <li class="menu-item">
                            <span class="menu-label menu-label_success">
								Приход&nbsp;товара
							</span>
                            <a class="menu-link"
                               href="{% url 'priceapp:product_update' %}">
                                Обновление цен
                            </a>
                        </li>
                        <li class="menu-item">
							<span class="menu-label menu-label_success">
								ICQ
							</span>
                            <a class="menu-link"
                               href="{% url 'priceapp:product_icq_update' %}">
                                Обновление цен
                            </a>
                        </li>
                        <li class="menu-item">
                            <a class="menu-link"
                               href="{% url 'priceapp:product_create' %}">
                                Добавление товара
                            </a>
                        </li>
                        <li class="menu-item">
							<span class="menu-label menu-label_success">
								ОПАСНО!
							</span>
                            <a class="menu-link" href="/admin/"
                               target="_blank">
                                Панель администратора
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>
<div class="Middle Middle_top middle-margin-null">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">
                    Ценники
                </h1>
            </div>
        </div>
    </div>
    {% block page_content %}{% endblock %}
</div>
<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>
</body>
</html>

templates/priceapp/big_sale_tags.html
{% load static %}
<tbody class="big-tags-layout">

<tr class="big-sale-first-line">
    <td class="big-sale-category"
        style="font-size: calc(min(25px / {{ tag.category|length }} * 12, 25px));"
    >{{ tag.category }}</td>

    <td class="big-sale-discount-type"
        style="font-size: calc(min(25px / {{ tag.discount_type|length }} * 15, 25px));"
    >{{ tag.discount_type }}</td>
</tr>

<tr class="big-second-line">
    <td class="big-product-name"
        style="font-size: calc(min(40px / {{ tag.name|length }} * 14, 40px));"
        colspan="2"
    >{{ tag.name }}</td>
</tr>

<tr class="big-sale-third-line">
    <td class="big-sale-old-price"
        style="font-size: calc(min(38px / {{ tag.old_price|make_list|length }} * 7, 70px));"
    ><p></p>{{ tag.old_price }}</td>

    <td {% if tag.red_price %}
        class="big-sale-price red-price"
    {% else %}
        class="big-sale-price black-price"
    {% endif %}
        style="font-size: calc(min(38px / {{ tag.price|make_list|length }} * 7, 70px));"
    >{{ tag.price }}</td>
</tr>

<tr class="big-fourth-line">
    <td class="big-country"
        style="font-size: calc(min(12px / {{ tag.country|length }} * 26, 12px));"
    >{{ tag.country }}</td>
    {% now 'd.m.Y' as date %}
    <td class="big-date"
        style="font-size: calc(min(12px / {{ date|length }} * 26, 12px));"
    ><em>{{ date }}</em></td>
</tr>

</tbody>

templates/priceapp/big_tags.html
{% load static %}
<tbody class="big-tags-layout">

<tr class="big-first-line">
    <td colspan="2"
        style="font-size: calc(min(25px / {{ tag.category|length }} * 24, 25px));"
    >{{ tag.category }}</td>
</tr>

<tr class="big-second-line">
    <td class="big-product-name"
        style="font-size: calc(min(40px / {{ tag.name|length }} * 14, 40px))"
        colspan="2">{{ tag.name }}</td>
</tr>

<tr class="big-third-line">
    <td {% if tag.red_price %}
        class="red-price"
    {% else %}
        class="black-price"
    {% endif %}
        style="font-size: calc(min(70px / {{ tag.price|make_list|length }} * 7, 70px));"
        colspan="2"
    >{{ tag.price }}</td>
</tr>

<tr class="big-fourth-line">
    <td class="big-country"
        style="font-size: calc(min(12px / {{ tag.country|length }} * 26, 12px));"
    >{{ tag.country }}</td>
    {% now 'd.m.Y' as date %}
    <td class="big-date"
        style="font-size: calc(min(12px / {{ date|length }} * 26, 12px));"
    ><em>{{ date }}</em></td>
</tr>

</tbody>

templates/priceapp/printsheet_form.html
{% extends 'priceapp/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block page_content %}
    <div>
        <div class="Section-content">
            <div class="Order-block Order-block_OPEN" id="login">
                <header class="Section-header Section-header_sm">
                    <h2 class="Section-title">Сканер штрих-кода</h2>
                </header>
                <div class="Cards">
                    {% for tag in tag_list %}
                        <div class="Card" id="{{ tag.size }}">
                            <form class="form Cart" method="post">
                                {% csrf_token %}
                                {% with 'sample_tag/'|add:tag.size|add:'-'|add:tag.is_discount.1|add:'.jpg' as image %}
                                    <img src="{% static image %}"
                                         alt="{{ image }}" class="sample-tag">
                                {% endwith %}
                                {% if tag.size == last_scan.tag.size and tag.is_discount.0 == last_scan.tag.is_discount %}
                                    {% if message_user %}
                                        <p class="red-price">Товар {{ message_user }}</p>
                                        <p class="red-price">не найден!</p>
                                    {% else %}
                                        <p class="black-price">Последний добавленный:</p>
                                        <p class="green-text">{{ last_scan.product }}</p>
                                    {% endif %}
                                    <p>&#8595; <em>{{ form.input_line.label }}</em> &#8595;</p>
                                    {{ form.input_line|attr:"autofocus" }}
                                {% else %}
                                    <p>&nbsp;</p>
                                    <p>&nbsp;</p>
                                    <p>&#8595; <em>{{ form.input_line.label }}</em> &#8595;</p>
                                    {{ form.input_line }}
                                {% endif %}
                                {% with 'value:'|add:tag.size as size %}
                                    {{ form.size|attr:size }}
                                {% endwith %}
                                {% with 'value:'|add:tag.is_discount.1 as is_discount %}
                                    {{ form.is_discount|attr:is_discount }}
                                {% endwith %}
                            </form>
                        </div>
                    {% endfor %}
                </div>
                <div class="add-custom-tag">
                    <div class="wrap wrap-add-custom-tag">
                        <h6 class="Middle-title">Добавить ценник по уценки:
                        </h6>
                        <div class="Middle-header Middle-header-free-form">
                            <form class="row free-form" id="free_form"
                                  method="post">
                                {% csrf_token %}
                                {% for field in free_form %}
                                    <p>{{ field.label }}<br>{{ field }}</p>
                                {% endfor %}
                                <button class="btn" type="submit"
                                >Добавить
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="Order-footer printsheet-button-area">
                    <a class="btn btn_success btn_muted Order-btnReg"
                       href="{% url 'priceapp:printsheet_delete' %}">
                        Очистить
                    </a>
                    <a class="btn btn_success Order-btnReg"
                       href="{% url 'priceapp:printsheet_print' %}"
                       target="_blank">
                        Сформировать
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/priceapp/product_update.html
{% extends 'priceapp/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block page_content %}
    <div>
        <div class="wrap">
            <form class="Section-content" id="file" method="post"
                  enctype="multipart/form-data">
                <div class="Order-block Order-block_OPEN" id="login">
                    <header class="Section-header Section-header_sm">
                        <h2 class="Section-title">
                            Поступление товара
                        </h2>
                    </header>
                    <div class="Cards" style="width: 100%">
                        {% csrf_token %}
                        {% if message_user %}
                            <h4 class="form-error">{{ message_user }}</h4>
                        {% else %}
                            <h4>Скачайте и заполните файл по ссылке: <a
                                    class="btn btn_success button-download"
                                    href="{% static 'product_update.csv' %}">СКАЧАТЬ</a>
                            </h4>
                        {% endif %}
                        <div class="form Cart" style="margin-left: 10px">
                            Загрузите заполненный файл:
                            <div>
                                {{ form.file|attr:'class:btn btn_success Order-btnReg button-download-form' }}
                                <button class="btn btn_success Order-btnReg"
                                        type="submit">
                                    Загрузить
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="wrap">
            <div class="block-instruction-update-product Cards">
                <div class="Card block-video-instruction">
                    <div class="row-instruction-by-update-price">
                        <h2>
                            &#9658;
                            <a href="{% url 'priceapp:update_instruction' %}"
                            >ИНСТРУКЦИЯ ТУТ</a>
                            &#9668;
                        </h2>
                    </div>
                    {#                    <div>#}
                    {#                        <video src="{% static '2023-06-09 11-35-34.mp4' %}"#}
                    {#                               controls class="video-instruction"></video>#}
                    {#                    </div>#}
                </div>
                <div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/priceapp/product_update_instruction.html
{% extends 'priceapp/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block page_content %}
    <div>
        <div class="wrap">
            <div class="Section-content">
                <div class="Order-block Order-block_OPEN" id="login">
                    <header class="Section-header Section-header_sm">
                        <h2 class="Section-title">
                            Инструкция
                        </h2>
                    </header>
                    <div class="Cards" style="width: 100%">
                        <div class="Cart" style="margin-left: 10px;">
                            <video src="{% static '2023-06-29 19-02-30.mkv' %}"
                                   controls class="video-instruction"></video>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}